### ISSUE TITLE
Invalid Image Reference in infrastructure-components.yaml in v0.10.x

### ISSUE THREAD

**Issue by broboa** [liquidmetal-dev/cluster-api-provider-microvm#345]
**What happened:**
The `capmvm-controller-manager` pod in the `capmvm-system` namespace fails to start due to an `ErrImagePull`. The image reference in the `infrastructure-components.yaml` for v0.10.1 points to an invalid container registry:

```
ghcr.io/liquidmetal-v0.10.1/cluster-api-provider-microvm:v0.10.1
```

Attempting to pull the image manually also fails with a `400 Bad Request` error, indicating the registry path is malformed or incorrect.

---

**What did you expect to happen:**
Expected the controller manager pod to start successfully using a valid image, e.g.:

```
ghcr.io/liquidmetal-dev/cluster-api-provider-microvm:v0.10.1
```

---

**How to reproduce it:**

1. Follow the Liquid Metal docs to configure `clusterctl.yaml` using v0.10.1:

```yaml
providers:
  - name: "microvm"
    url: "https://github.com/liquidmetal-dev/cluster-api-provider-microvm/releases/v0.10.1/infrastructure-components.yaml"
    type: "InfrastructureProvider"
```

2. Run `clusterctl init --infrastructure microvm`
3. Observe that the `capmvm-controller-manager` pod fails with `ErrImagePull`

---

**Anything else you would like to add:**

* This appears to be a publishing or templating issue affecting both v0.10.1 and v0.10.0.
* All previous versions used `ghcr.io/weaveworks-liquidmetal` or `ghcr.io/weaveworks`.
* The expected working image is likely under: `ghcr.io/liquidmetal-dev/cluster-api-provider-microvm:v0.10.1`
* Suggest auditing the CI/CD pipeline or release script that generates the YAML manifests.

---

**Environment:**

* capmvm version: v0.10.1
* OS (e.g. from `/etc/os-release`): RHEL9
---
